# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-12 13:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='collaborators',
            field=models.EmailField(max_length=50),
        ),
        migrations.AlterField(
            model_name='task',
            name='isComplete',
            field=models.BooleanField(default='false'),
        ),
        migrations.AlterField(
            model_name='task',
            name='isOwner',
            field=models.BooleanField(default='false'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=50),
        ),
    ]
