# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-12 22:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0003_auto_20160212_2004'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='collaborators',
        ),
        migrations.AddField(
            model_name='task',
            name='collaborator1',
            field=models.EmailField(blank='true', max_length=50),
        ),
        migrations.AddField(
            model_name='task',
            name='collaborator2',
            field=models.EmailField(blank='true', max_length=50),
        ),
        migrations.AddField(
            model_name='task',
            name='collaborator3',
            field=models.EmailField(blank='true', max_length=50),
        ),
        migrations.AlterField(
            model_name='task',
            name='description',
            field=models.CharField(blank='true', max_length=5000),
        ),
    ]
