# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-12 22:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0004_auto_20160212_2214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='owner',
            field=models.IntegerField(),
        ),
    ]
